spring:
  thymeleaf:
    mode: LEGACYHTML5

logging:
  level:
     org.springframework.security: 'DEBUG'
     com.nomadays.sso: 'DEBUG'

sso:
  server:
    allowed-uris:
      - http://127.0.0.1:9090
      